// Build script: assembles worker.js from master.json + translations.json
// Run: node build-worker.js
const fs = require('fs');

const master = JSON.parse(fs.readFileSync('/tmp/master.json', 'utf8'));
const translations = JSON.parse(fs.readFileSync('/tmp/translations.json', 'utf8'));

// Mandarin already lives in master as `zh`; fold it into translations
translations.zh = {};
for (const d of master) {
  translations.zh[d.id] = {};
  for (const s of d.segments) translations.zh[d.id][s.id] = s.zh;
}

// strip the heavy zh field from master (now in translations)
for (const d of master) for (const s of d.segments) delete s.zh;

const LANGUAGES = {
  zh:  { label:'Mandarin',   native:'普通话',     code:'zh-CN', flag:'🇨🇳' },
  yue: { label:'Cantonese',  native:'廣東話',     code:'zh-HK', flag:'🇭🇰' },
  pa:  { label:'Punjabi',    native:'ਪੰਜਾਬੀ',    code:'pa-IN', flag:'🇮🇳' },
  hi:  { label:'Hindi',      native:'हिन्दी',     code:'hi-IN', flag:'🇮🇳' },
  ne:  { label:'Nepali',     native:'नेपाली',     code:'ne-NP', flag:'🇳🇵' },
  vi:  { label:'Vietnamese', native:'Tiếng Việt', code:'vi-VN', flag:'🇻🇳' },
  ar:  { label:'Arabic',     native:'العربية',    code:'ar-SA', flag:'🇸🇦' },
  ko:  { label:'Korean',     native:'한국어',      code:'ko-KR', flag:'🇰🇷' },
  ta:  { label:'Tamil',      native:'தமிழ்',      code:'ta-IN', flag:'🇮🇳' },
  fa:  { label:'Persian',    native:'فارسی',      code:'fa-IR', flag:'🇮🇷' },
};

const available = Object.keys(LANGUAGES).filter(k => translations[k] && Object.keys(translations[k]).length === master.length);

const worker = `// AUTO-GENERATED by build-worker.js — do not edit by hand.
// NAATI CCL bilingual interpreting practice, ${available.length} languages.

const LANGUAGES = ${JSON.stringify(LANGUAGES, null, 2)};

const AVAILABLE = ${JSON.stringify(available)};

const MASTER = ${JSON.stringify(master, null, 1)};

const TRANSLATIONS = ${JSON.stringify(translations)};

function buildSegment(dlgId, seg, langKey) {
  const L = LANGUAGES[langKey];
  const target = (TRANSLATIONS[langKey] && TRANSLATIONS[langKey][dlgId] && TRANSLATIONS[langKey][dlgId][seg.id]) || seg.en;
  if (seg.role === 'pro') {
    return { id: seg.id, marked: seg.marked, speaker: seg.speaker,
      lang: 'en-AU', interpretLang: L.code, audioLang: 'en',
      text: seg.en, modelAnswer: target, keyPoints: seg.keyPoints };
  }
  return { id: seg.id, marked: seg.marked, speaker: seg.speaker,
    lang: L.code, interpretLang: 'en-AU', audioLang: langKey,
    text: target, modelAnswer: seg.en, keyPoints: seg.keyPoints };
}

function buildDialogue(d, langKey) {
  return { id: d.id, topic: d.topic, title: d.title,
    scenario: d.scenario, scenarioZh: d.scenarioZh, language: langKey,
    segments: d.segments.map(s => buildSegment(d.id, s, langKey)) };
}

const SCORE_PROMPT = (seg, transcript, langLabel) => {
  const enToTarget = seg.lang === 'en-AU';
  const direction = enToTarget ? \`English → \${langLabel}\` : \`\${langLabel} → English\`;
  const targetLang = enToTarget ? langLabel : 'English';
  return \`You are a NAATI CCL examiner assessing an interpretation attempt.

Direction: \${direction}
Source (what was spoken):
"\${seg.text}"

Candidate's interpretation (into \${targetLang}):
"\${transcript}"

Model interpretation for reference:
"\${seg.modelAnswer}"

Key information to transfer: \${seg.keyPoints.join(' | ')}

NAATI CCL 0–5 marking scale:
5 — All key information conveyed accurately and naturally
4 — Most conveyed; one minor omission or inaccuracy
3 — Partially conveyed; some omissions but core meaning understood
2 — Limited; significant omissions or errors affecting meaning
1 — Very little correct; largely unclear
0 — Nothing meaningful

Respond with ONLY raw JSON (no markdown, no code fences):
{
  "score": <integer 0-5>,
  "passed": <boolean, true if score >= 3>,
  "feedback": "<2 sentences, specific and actionable>",
  "corrections": [ { "said": "<candidate>", "better": "<improved>", "why": "<brief>" } ],
  "keyPointsCovered": [ { "point": "<key point>", "covered": <boolean> } ]
}\`;
};

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const { pathname } = url;
    const cors = { 'Access-Control-Allow-Origin':'*', 'Access-Control-Allow-Methods':'GET, POST, OPTIONS', 'Access-Control-Allow-Headers':'Content-Type' };
    if (request.method === 'OPTIONS') return new Response(null, { headers: cors });

    if (pathname === '/api/languages') {
      return Response.json(AVAILABLE.map(k => ({ key:k, ...LANGUAGES[k] })), { headers: cors });
    }

    if (pathname === '/api/dialogues') {
      return Response.json(MASTER.map(d => ({
        id:d.id, topic:d.topic, title:d.title, scenario:d.scenario, scenarioZh:d.scenarioZh,
        segmentCount:d.segments.length, scoredCount:d.segments.filter(s=>s.marked).length,
      })), { headers: cors });
    }

    const m = pathname.match(/^\\/api\\/dialogue\\/(.+)$/);
    if (m) {
      const lang = url.searchParams.get('lang') || 'zh';
      const d = MASTER.find(x => x.id === m[1]);
      if (!d) return new Response('Not found', { status: 404 });
      if (!AVAILABLE.includes(lang)) return new Response('Language not available', { status: 404 });
      return Response.json(buildDialogue(d, lang), { headers: cors });
    }

    if (pathname === '/api/score' && request.method === 'POST') {
      try {
        const { dialogueId, segmentId, transcript, lang } = await request.json();
        if (!transcript || !transcript.trim()) return Response.json({ error:'No transcript' }, { status:400, headers:cors });
        const langKey = AVAILABLE.includes(lang) ? lang : 'zh';
        const d = MASTER.find(x => x.id === dialogueId);
        const segMaster = d && d.segments.find(s => s.id === segmentId);
        if (!segMaster) return Response.json({ error:'Not found' }, { status:404, headers:cors });
        const seg = buildSegment(dialogueId, segMaster, langKey);

        if (!env.DEEPSEEK_API_KEY) {
          return Response.json({ score:4, passed:true, feedback:'Demo mode.', corrections:[], keyPointsCovered:[] }, { headers:cors });
        }
        const resp = await fetch('https://api.deepseek.com/chat/completions', {
          method:'POST',
          headers:{ 'Authorization':\`Bearer \${env.DEEPSEEK_API_KEY}\`, 'Content-Type':'application/json' },
          body: JSON.stringify({ model:'deepseek-chat', max_tokens:600,
            messages:[{ role:'user', content: SCORE_PROMPT(seg, transcript, LANGUAGES[langKey].label) }] }),
        });
        const ai = await resp.json();
        if (ai.error) return Response.json({ error: ai.error.message }, { status:502, headers:cors });
        let raw = (ai.choices && ai.choices[0] && ai.choices[0].message && ai.choices[0].message.content) || '{}';
        const jm = raw.match(/\\{[\\s\\S]*\\}/);
        if (!jm) throw new Error('No JSON');
        const result = JSON.parse(jm[0]);
        result.score = Math.max(0, Math.min(5, result.score == null ? 0 : result.score));
        result.passed = result.score >= 3;
        return Response.json(result, { headers: cors });
      } catch (e) {
        return Response.json({ error: e.message }, { status:500, headers:cors });
      }
    }

    return env.ASSETS.fetch(request);
  },
};
`;

fs.writeFileSync('worker.js', worker);
console.log('worker.js built. Languages:', available.join(', '));
console.log('Size:', (worker.length / 1024).toFixed(1), 'KB');
