// Build script: assembles worker.js from master.json + translations.json
// Run: node build-worker.js
const fs = require('fs');

const master = JSON.parse(fs.readFileSync('/tmp/master.json', 'utf8'));
const translations = JSON.parse(fs.readFileSync('/tmp/translations.json', 'utf8'));

// Original 3 dialogues carry Mandarin inline as `zh`; new ones get zh from the
// translation batch. Merge: keep any translations.zh already present, then fill
// from master.zh where a segment still has it.
translations.zh = translations.zh || {};
for (const d of master) {
  translations.zh[d.id] = translations.zh[d.id] || {};
  for (const s of d.segments) {
    if (s.zh && !translations.zh[d.id][s.id]) translations.zh[d.id][s.id] = s.zh;
  }
}
// strip the heavy zh field from master (now in translations)
for (const d of master) for (const s of d.segments) delete s.zh;

const LANGUAGES = {
  zh:  { label:'Mandarin',   native:'普通话',     code:'zh-CN', flag:'🇨🇳' },
  yue: { label:'Cantonese',  native:'廣東話',     code:'zh-HK', flag:'🇭🇰' },
  pa:  { label:'Punjabi',    native:'ਪੰਜਾਬੀ',    code:'pa-IN', flag:'🇮🇳' },
  hi:  { label:'Hindi',      native:'हिन्दी',     code:'hi-IN', flag:'🇮🇳' },
  ne:  { label:'Nepali',     native:'नेपाली',     code:'ne-NP', flag:'🇳🇵' },
  vi:  { label:'Vietnamese', native:'Tiếng Việt', code:'vi-VN', flag:'🇻🇳' },
  ar:  { label:'Arabic',     native:'العربية',    code:'ar-SA', flag:'🇸🇦' },
  ko:  { label:'Korean',     native:'한국어',      code:'ko-KR', flag:'🇰🇷' },
  ta:  { label:'Tamil',      native:'தமிழ்',      code:'ta-IN', flag:'🇮🇳' },
  fa:  { label:'Persian',    native:'فارسی',      code:'fa-IR', flag:'🇮🇷' },
};

const available = Object.keys(LANGUAGES).filter(k => translations[k] && Object.keys(translations[k]).length === master.length);

const worker = `// AUTO-GENERATED by build-worker.js — do not edit by hand.
// Data module: dialogues, translations, and segment builders.

export const LANGUAGES = ${JSON.stringify(LANGUAGES, null, 2)};

export const AVAILABLE = ${JSON.stringify(available)};

export const MASTER = ${JSON.stringify(master, null, 1)};

export const TRANSLATIONS = ${JSON.stringify(translations)};

export function buildSegment(dlgId, seg, langKey) {
  const L = LANGUAGES[langKey];
  const target = (TRANSLATIONS[langKey] && TRANSLATIONS[langKey][dlgId] && TRANSLATIONS[langKey][dlgId][seg.id]) || seg.en;
  if (seg.role === 'pro') {
    return { id: seg.id, marked: seg.marked, speaker: seg.speaker,
      lang: 'en-AU', interpretLang: L.code, audioLang: 'en',
      text: seg.en, modelAnswer: target, keyPoints: seg.keyPoints };
  }
  return { id: seg.id, marked: seg.marked, speaker: seg.speaker,
    lang: L.code, interpretLang: 'en-AU', audioLang: langKey,
    text: target, modelAnswer: seg.en, keyPoints: seg.keyPoints };
}

export function buildDialogue(d, langKey) {
  return { id: d.id, topic: d.topic, title: d.title,
    scenario: d.scenario, scenarioZh: d.scenarioZh, language: langKey,
    segments: d.segments.map(s => buildSegment(d.id, s, langKey)) };
}
`;

fs.writeFileSync('data.js', worker);
console.log('data.js built. Languages:', available.join(', '), '| dialogues:', master.length);
console.log('Size:', (worker.length / 1024).toFixed(1), 'KB');
